"""empty message

Revision ID: 57cc4ebb4f12
Revises: d911ec0c2801
Create Date: 2023-06-16 17:15:53.744026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cc4ebb4f12'
down_revision = 'd911ec0c2801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
